# Generated by Django 2.2a1 on 2019-02-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='actType',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
