# Generated by Django 2.2a1 on 2019-02-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
