# Generated by Django 2.2a1 on 2019-02-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
