# Generated by Django 2.2a1 on 2019-02-08 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 18, 43, 10, 742929, tzinfo=utc), null=True),
        ),
    ]
