# Generated by Django 2.2a1 on 2019-02-09 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0010_auto_20190209_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 7, 8, 59, 262787, tzinfo=utc), null=True),
        ),
    ]
