# Generated by Django 2.2a1 on 2019-02-10 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0012_auto_20190210_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 15, 52, 59, 136688, tzinfo=utc), null=True),
        ),
    ]
